#!/usr/bin/env php
<?php
/**
 * Console manipulation for the aplication
 *
 * Please report bugs on https://github.com/espino316/rsphp/issues
 *
 * @author Luis Espino <luis@espino.info>
 * @copyright Copyright (c) 2016, Luis Espino. All rights reserved.
 * @license MIT License
 */

//  Before anything, make a dump-autoload,
//  to create the autoload file
//  if the file is not existing only

$cwd = getcwd();
$rsPhpPath = dirname( __FILE__ );

require_once "$rsPhpPath/vendor/autoload.php";

if ( file_exists( "$rsPhpPath/public/index.php" ) ) {
    require_once "$rsPhpPath/public/index.php";
} // end if file exists

use RSPhp\Framework\RS;
use RSPhp\Framework\File;

$command = RS::processStdIn( $argv );
$params = $command["parameters"];
$command = $command["command"];

if ( $command == 'version' ) {
	echo RS::$version;
	return;
}

if ( $command == "help" ) {
    $content = File::read( $rsPhpPath . DS . "rsphp_help" );
    RS::printLine( $content );
}// end if help

if ( $command == 'cleanapp' ) {
	RS::cleanApp();
	return;
} // end if cleanapp

if ( $command == "connection list" ) {
    RS::listConnections();
} // end if controller list

if ( $command == "controller list" ) {
    RS::listControllers();
} // end if controller list

if ( $command == "model list" ) {
    RS::listModels();
} // end if controller list

if ( $command == "route list" ) {
    RS::listRoutes();
} // end if controller list

if ( $command == "datasource list" ) {
    RS::listDataSources();
} // end if controller list

if ( $command == "controller create" ) {

	if ( !isset( $params["name"] ) ) {
		RS::printLine( "Controller name must be specified" );
		return;
    } // end if not doc

    if ( !isset( $params["doc"] ) ) {
		RS::printLine( "Controller documentation must be specified" );
		return;
    } // end if not doc

    RS::printLine("Creating controller");
	RS::createController( $params["name"], $params["doc"] );
	return;
}

//	function create model
//	php rs.php model create <tableName>
//	php rs.php model create attachments
if ( $command == "model create" ) {

    if ( !isset( $params["table"] ) ) {
        RS::printLine( "Table name must be specified." );
    } // end if isset param

	RS::printLine("Model create");
	//	The table name
	$tableName = strtolower( $params["table"] );

	RS::printLine("Beginning creation of model for table $tableName...");

	// Model Create
	RS::createModel( $tableName );
	return;
}

if ( $command == "connection add" ) {

    if (count($params) === 0) {
        RS::printLine("What's your connection name?: (default)");
        $name = RS::readLine();
        $name = ($name) ? $name : 'default';

        RS::printLine("What's your db engine?: (mysql | pgsql | sqlsrv | dblib)");
        $driver = RS::readLine();
        while (!$driver) {
            RS::printLine("You must provide a db driver");
            RS::printLine("What's your db engine?: (mysql | pgsql | sqlsrv | dblib)");
            $driver = RS::readLine();
        } // end while not drive

        RS::printLine("What's your server name or IP?:");
        $hostName= RS::readLine();
        while (!$hostName) {
            RS::printLine("You must provide a server name");
            RS::printLine("What's your server name or IP?:");
            $hostName = RS::readLine();
        } // end while not drive

        RS::printLine("What's your database name?:");
        $databaseName = RS::readLine();
        while (!$databaseName) {
            RS::printLine("You must provide a database name");
            RS::printLine("What's your database name?:");
            $databaseName = RS::readLine();
        } // end while not drive

        RS::printLine("What's the db user's name?:");
        $userName = RS::readLine();
        while (!$userName) {
            RS::printLine("You must provide an user name");
            RS::printLine("What's the db user's name?:");
            $userName = RS::readLine();
        } // end while not drive

        RS::printLine("What's the db user's password?:");
        $pwd = RS::readLine();
        if (!$pwd) {
            RS::printLine("Empty passwords is a very insecure configuration");
        } // end while not drive

        RS::printLine("Any specific port?:");
        $port = RS::readLine();

        RS::addConnection(
            $name,
            $driver,
            $hostName,
            $databaseName,
            $userName,
            $pwd,
            $port
        );

        return;
    } // end if

    $port = null;

    if ( isset( $params["port"] ) ) {
        $port = $params["port"];
    } // end if port

    RS::addConnection(
        $params["name"],
        $params["driver"],
        $params["hostName"],
        $params["databaseName"],
        $params["userName"],
        $params["password"],
        $port
    );

    RS::printLine( "Connection added." );
} // end if command is connection add

if ( $command == "datasource add" ) {
    if ( isset( $params["text"] ) ) {
        $text = $params["text"];
        $isFile = false;
    } // end if text

    if ( isset( $params["file"] ) ) {
        $text = $params["file"];
        $isFile = true;
    } // end if file

    RS::addDataSource(
        $params["connection"],
        $params["name"],
        $params["type"],
        $text,
        $isFile
    );
} // end if command datasource add

if ( $command == "route add" ) {

    RS::addRoute(
        $params["method"],
        $params["url"],
        $params["newUrl"]
    );

    RS::printLine( "Route added." );
} // end if command is connection add

if ( $command == "view add" ) {

    if ( ! array_key_exists( "name", $params ) ) {
        throw new Exception( "Must specify view name" );
    } // end if not array key exists

    if ( ! array_key_exists( "type", $params ) ) {
        $params["type"] = "content";
    } // end if not array key exists

    RS::createView(
        $params["name"],
        $params["type"]
    ); // end createView
} // end if command is view add

if ( $command == "view create new" ) {
	$tableName = $params["table"];
	RS::createViewNewRecord( $tableName );
	return;
} // end if view create new

//  If create app, make directories structure
if ( $command == "init" ) {
    if ( isset( $params["default"] ) ) {
        $dir = "default";
    } else {
        $dir = $params["default"];
    } // end if

    RS::init( $dir );
} // end if create app

RS::printLine("");
